language: php
env:
  global:
    - secure: "E2Qf67xzlsxrORU1I8bRbN0XakxhUUPL3dxLc8S9WI5YbOiRzMIvaWWi2dRRLj8/A6VsbM47yxibnGew6NCVAHPwgIql+Yd2GBNYc0HnVkzMfmIDzOJUFT+mlaRcy5l5mjSYk1XoedJpwFDA7Igt6MyLS3CMjadCEIT3oA5E6jC5/0AvO2t4JmlK/VK/6Svmf3j+RESvR05Xtvm8GNvx64PK9G6mbe7owrMn0axGF0kKpyXhWtcho9q/UI6K2qEdb6pPZFCI+rA5bIatJ2+y1vSZT5TZicMN3EuwDeDD9xnQu7z4Fm5a8DFVQY2dKrAJSFOkKPnb7fbMCE+9f981uvSesIH4hnJcKTBBKQHJkbESMKiObBqFVXicbTbASRx2RwrTuQEtxGrqSXkJEYXEUl4RqrZs1XMWDG0xbHbuZN538Kz8j0G5TUOAfayESogGvtxlLfhBipg+7rz26m3ED2y8wTxzsooB2Ushuz5pEHxMn+DsIWnDQxLxsuNOo+xEifapHSEwfXbkVcDMRAuC2R7Znr30SONNoG0Nj3JjPSTpopSPP/tqOHIArdKN9cH1MdqLodF2jUH5a75nOUOnOf0M9NXMctGxv7VGcsf/vXKhFBnXqpCu9MQwGFUVyXa8Lfv7Ap5PCGBIdhe8oJrF2dE5q7LsXKjopBhlNHbXXog="
php:
  - '5.6'
  - '7.1'
  - '7.2'
branches:
  only:
    - /.*/
install: composer install
script: vendor/bin/phpunit
jobs:
  include:
    - stage: coverage report
      php: 7.2
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
