language: php
php:
  - '5.6'
  - '7.1'
  - '7.2'
branches:
  only:
    - /.*/
install: composer install
script: vendor/bin/phpunit
jobs:
  include:
    - stage: coverage report
      php: 7.2
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
